server:
  port: 8080

spring:
  application:
    name: grade-client


security:
  jwt:
    secret: Y2hkLWdyYWRlLW1hbmFnZW1lbnQtc2VjcmV0LWtleS0yMDI1LTMyYnl0ZXM=
    expiration: 86400
  aes:
    secret-key: DqWW5+9DjS+rreSFA7MaiHiGfXUI9CjnrpHn5EJZtrA=


remote:
  server:
    url: http://localhost:8081/rpc

logging:
  level:
    com.chd.client: DEBUG