server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chd_grade_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Scl03282219
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  aes:
    secret-key: DqWW5+9DjS+rreSFA7MaiHiGfXUI9CjnrpHn5EJZtrA=
  jwt:
    secret: Y2hkLWdyYWRlLW1hbmFnZW1lbnQtc2VjcmV0LWtleS0yMDI1LTMyYnl0ZXM=
    expiration: 86400

logging:
  level:
    com.chd.score: DEBUG